framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Comment
            initial_marking: '%comment.status.submitted%'
            places:
                - '%comment.status.submitted%'
                - '%comment.status.ham%'
                - '%comment.status.potential_spam%'
                - '%comment.status.spam%'
                - '%comment.status.rejected%'
                - '%comment.status.ready%'
                - '%comment.status.published%'
            transitions:
                accept:
                    from: '%comment.status.submitted%'
                    to:   '%comment.status.ham%'
                might_be_spam:
                    from: '%comment.status.submitted%'
                    to:   '%comment.status.potential_spam%'
                reject_spam:
                    from: '%comment.status.submitted%'
                    to:   '%comment.status.spam%'
                publish:
                    from: '%comment.status.potential_spam%'
                    to:   '%comment.status.ready%'
                reject:
                    from: '%comment.status.potential_spam%'
                    to:   '%comment.status.rejected%'
                publish_ham:
                    from: '%comment.status.ham%'
                    to:   '%comment.status.ready%'
                reject_ham:
                    from: '%comment.status.ham%'
                    to:   '%comment.status.rejected%'
                optimize:
                    from: '%comment.status.ready%'
                    to:   '%comment.status.published%'
